# Generated by Django 4.1.1 on 2023-02-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='accepted',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
