# Generated by Django 4.1.1 on 2023-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0004_alter_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
