# Generated by Django 4.1.1 on 2023-02-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0005_alter_request_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
